In [1]:
import tensorflow as tf
import numpy as np

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.set_random_seed(777)

In [3]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
# xy

In [9]:
# x_data

In [10]:
# y_data

In [8]:
x_data.shape, y_data.shape

((25, 3), (25, 1))

In [11]:
# placesholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [12]:
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [14]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [15]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [19]:
# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001) :
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict = {X : x_data, Y : y_data})
    
    if step % 1000 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)
        
# 2000 Cost :  24.722479 
# Prediction : 
#  [[154.42892]
#  [185.5586 ]
#  [182.90646]
#  [198.08952]
#  [142.52043]
#  [103.55179]
#  [146.7915 ]
#  [106.70152]
#  [172.15207]
#  [157.13037]
#  [142.55319]
#  [140.17581]
#  [190.05005]
#  [159.59952]
#  [147.35217]
#  [187.2683 ]
#  [153.33151]
#  [175.38618]
#  [181.37059]
#  [162.1332 ]
#  [172.44305]
#  [173.06041]
#  [164.73372]
#  [158.24257]
#  [192.79166]]

0 Cost :  21027.002 
Prediction : 
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347944 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189451 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084761 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.986364 ]]
1000 Cost :  46.33358 
Prediction : 
 [[155.79349]
 [185.46013]
 [183.79823]
 [197.92882]
 [142.94724]
 [101.91647]
 [145.47525]
 [104.10523]
 [170.27351]
 [152.73247]
 [141.92949]
 [138.35954]
 [192.1013 ]
 [162.8083 ]
 [145.64487]
 [186.24963]
 [157.22314]
 [173.4941 ]
 [183.77397]
 [164.26617]
 [171.05286]
 [171.97366]
 [163.87851]
 [162.25095]
 [193.49663]]
2000 Cost :  24.722479 
Prediction : 
 [[154.42892]
 [185.5586 ]
 [182.90646]
 [198.08952]
 [142.52043]
 [103.55179]
 [146.7915 ]
 [106.70152]
 [172.15207]
 [157.13037]
 [142.55319]
 [140.17581]
 [190.05005]
 [159.59952]
 [147.35217]
 [187.2683 ]
 [

In [18]:
# Launch the graph in a session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(3001) :
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict = {X : x_data, Y : y_data})
    
    if step % 1000 == 0 :
        print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)
        
# 3000 Cost :  15.039162 
# Prediction : 
#  [[153.63275]
#  [185.52725]
#  [182.33676]
#  [198.22313]
#  [142.10425]
#  [104.51659]
#  [147.75331]
#  [108.59205]
#  [173.2588 ]
#  [159.90512]
#  [142.9812 ]
#  [141.2954 ]
#  [188.70454]
#  [157.46344]
#  [148.54012]
#  [187.87003]
#  [150.66821]
#  [176.80267]
#  [179.82532]
#  [160.78732]
#  [173.4355 ]
#  [173.70831]
#  [165.38637]
#  [155.6779 ]
#  [192.25797]]

0 Cost :  21027.002 
Prediction : 
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347944 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189451 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084761 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.986364 ]]
1000 Cost :  46.33358 
Prediction : 
 [[155.79349]
 [185.46013]
 [183.79823]
 [197.92882]
 [142.94724]
 [101.91647]
 [145.47525]
 [104.10523]
 [170.27351]
 [152.73247]
 [141.92949]
 [138.35954]
 [192.1013 ]
 [162.8083 ]
 [145.64487]
 [186.24963]
 [157.22314]
 [173.4941 ]
 [183.77397]
 [164.26617]
 [171.05286]
 [171.97366]
 [163.87851]
 [162.25095]
 [193.49663]]
2000 Cost :  24.722479 
Prediction : 
 [[154.42892]
 [185.5586 ]
 [182.90646]
 [198.08952]
 [142.52043]
 [103.55179]
 [146.7915 ]
 [106.70152]
 [172.15207]
 [157.13037]
 [142.55319]
 [140.17581]
 [190.05005]
 [159.59952]
 [147.35217]
 [187.2683 ]
 [

In [20]:
print(sess.run(hypothesis, feed_dict = {X : [[100, 70, 101]]}))
print(sess.run(hypothesis, feed_dict = {X : [[60, 70, 110], [90, 100, 80]]}))

[[181.73277]]
[[145.86266]
 [187.2313 ]]
