In [1]:
import tensorflow as tf
tf.set_random_seed(777)

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x_data = [[1, 2, 1], 
          [1, 3, 2], 
          [1, 3, 4], 
          [1, 5, 5], 
          [1, 7, 5], 
          [1, 2, 5], 
          [1, 6, 6], 
          [1, 7, 7]]
y_data = [[0, 0, 1], 
          [0, 0, 1], 
          [0, 0, 1], 
          [0, 1, 0], 
          [0, 1, 0], 
          [0, 1, 0], 
          [1, 0, 0], 
          [1, 0, 0]]

In [4]:
import numpy as np
print(np.array(x_data).shape, np.array(y_data).shape)

(8, 3) (8, 3)


In [5]:
# Evaluate our model using this test dataset
x_test = [[2, 1, 1], 
          [3, 1, 2], 
          [3, 3, 4]]
y_test = [[0, 0, 1], 
          [0, 0, 1], 
          [0, 0, 1]]

In [6]:
print(np.array(x_test).shape, np.array(y_test).shape)

(3, 3) (3, 3)


In [7]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

In [8]:
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [10]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

In [19]:
train = tf.train.GradientDescentOptimizer(learning_rate = 1.0).minimize(cost)

In [20]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [21]:
# Launch graph
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    
    for step in range(201) :
        cost_val, W_val, _ = sess.run([cost, W, train], 
                                      feed_dict = {X : x_data, Y : y_data})
        if step % 50 == 0 :
            print(step, cost_val, W_val)
    
    print("Prediction : ", sess.run(prediction, feed_dict = {X : x_test}))
    print("Accuracy : ", sess.run(accuracy, feed_dict = {X : x_test, Y : y_test}))

0 5.73203 [[ 0.06390554  1.0461044  -0.8459846 ]
 [-3.028856    1.4300685   2.4986644 ]
 [-1.9776635   1.1646577  -1.2388651 ]]
50 3.9471197 [[-3.6428652  -0.818304    4.725195  ]
 [ 1.9954069  -2.5055754   1.4100466 ]
 [ 1.1329098  -0.29788077 -2.8869019 ]]
100 5.1370263 [[-6.0651507   0.39654976  5.932626  ]
 [ 1.8737042   0.24304712 -1.2168727 ]
 [ 0.7495975   1.5118697  -4.313339  ]]
150 9.1461735 [[-8.213901   1.4140018  7.063922 ]
 [ 1.0567447 -0.6311492  0.4742844]
 [ 0.5517032  0.6018462 -3.2054226]]
200 8.280764 [[-10.081952     2.5785632    7.7674136 ]
 [  0.9974371   -0.43248463   0.33492696]
 [  1.3210105    0.22629225  -3.5991762 ]]
Prediction :  [2 2 2]
Accuracy :  1.0


In [ ]:
# learning_rate = 1.5

# 0 5.73203 [[-0.30548954  1.2298503  -0.66033536]
#  [-4.3907      2.2967086   2.9938684 ]
#  [-3.345107    2.0974321  -0.80419564]]
# 50 nan [[nan nan nan]
#  [nan nan nan]
#  [nan nan nan]]
# 100 nan [[nan nan nan]
#  [nan nan nan]
#  [nan nan nan]]
# 150 nan [[nan nan nan]
#  [nan nan nan]
#  [nan nan nan]]
# 200 nan [[nan nan nan]
#  [nan nan nan]
#  [nan nan nan]]
# Prediction :  [0 0 0]
# Accuracy :  0.0

In [ ]:
# learning_rate = 1.0

# 0 5.73203 [[ 0.06390554  1.0461044  -0.8459846 ]
#  [-3.028856    1.4300685   2.4986644 ]
#  [-1.9776635   1.1646577  -1.2388651 ]]
# 50 3.9471197 [[-3.6428652  -0.818304    4.725195  ]
#  [ 1.9954069  -2.5055754   1.4100466 ]
#  [ 1.1329098  -0.29788077 -2.8869019 ]]
# 100 5.1370263 [[-6.0651507   0.39654976  5.932626  ]
#  [ 1.8737042   0.24304712 -1.2168727 ]
#  [ 0.7495975   1.5118697  -4.313339  ]]
# 150 9.1461735 [[-8.213901   1.4140018  7.063922 ]
#  [ 1.0567447 -0.6311492  0.4742844]
#  [ 0.5517032  0.6018462 -3.2054226]]
# 200 8.280764 [[-10.081952     2.5785632    7.7674136 ]
#  [  0.9974371   -0.43248463   0.33492696]
#  [  1.3210105    0.22629225  -3.5991762 ]]
# Prediction :  [2 2 2]
# Accuracy :  1.0

In [ ]:
# learning_rate = 0.1

# 0 5.73203 [[ 0.7288166   0.7153621  -1.1801533 ]
#  [-0.57753736 -0.12988332  1.6072978 ]
#  [ 0.48373488 -0.51433605 -2.02127   ]]
# 50 1.3068547 [[-0.03424712  0.6126727  -0.31440023]
#  [-0.18752575 -0.19023973  1.2776425 ]
#  [-0.18732947 -0.16467495 -1.6998668 ]]
# 100 0.9537603 [[-0.52009284  0.45806164  0.32605675]
#  [ 0.11236367 -0.04872466  0.836238  ]
#  [-0.3214388  -0.27116382 -1.4592681 ]]
# 150 0.76444477 [[-0.87777096  0.34463155  0.7971652 ]
#  [ 0.2841537   0.10438942  0.5113338 ]
#  [-0.36992022 -0.38639486 -1.2955555 ]]
# 200 0.67090875 [[-1.1588541   0.28058422  1.1422957 ]
#  [ 0.37609792  0.19073224  0.33304682]
#  [-0.35536593 -0.44033223 -1.2561723 ]]
# Prediction :  [2 2 2]
# Accuracy :  1.0